export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCEED = 'FETCH_WEATHER_SUCCEED';
export const FETCH_CITY_WEATHER = 'FETCH_CITY_WEATHER';
export const FETCH_CITY_WEATHER_SUCCEED = 'FETCH_CITY_WEATHER_SUCCEED';
